// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = (function() {

    function _Class() {}

    /*
    */


    _Class.prototype.find = function(nodeName, index) {
      if (nodeName == null) {
        nodeName = "*";
      }
      if (index == null) {
        index = 0;
      }
      return this._newChain("//" + nodeName).index(index);
    };

    /*
    */


    _Class.prototype.element = function(nodeName, index) {
      if (nodeName == null) {
        nodeName = "*";
      }
      if (index == null) {
        index = 0;
      }
      return this._newChain("/" + nodeName).index(index);
    };

    /*
    */


    _Class.prototype.toString = function() {
      return "";
    };

    /*
    */


    _Class.prototype._newChain = function(nodeName) {};

    return _Class;

  })();

}).call(this);
